#ifndef SYMBOLS_H_
#define SYMBOLS_H_

enum
{
	IDS_CREATE_VOLUMEBUILDER_COMMAND = 10000,
	IDS_READ_VOLUME_COMMAND,
	IDS_CREATE_VOLUME_COMMAND,
	IDS_SUBSTRACT_OBJECTS_COMMAND,
	IDS_SAMPLE_FIELDOBJECT_COMMAND,
	IDS_SAMPLE_FIELDLIST_COMMAND,
	IDS_FCHECKERBOX,
	IDS_NEXTNEIGHBOR_LAYER,
	IDS_CREATE_MULTIINSTANCE_COMMAND,
	IDS_READ_MULTIINSTACE_COMMAND,
	_DUMMY_ELEMENT_
};

#endif